import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Tailwind Components - Auth",
	description: "Generated by Maxirpc",
};

export default function AuthLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="es" className="h-full bg-white">
			<body className={`h-full ${inter.className}`}>{children}</body>
		</html>
	);
}
